// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUqMAoH8UqTH2TotAKU44b5-3zqG1Prbc',
    appId: '1:84806354543:web:d4f84307326e8defff2f9a',
    messagingSenderId: '84806354543',
    projectId: 'my-n-n',
    authDomain: 'my-n-n.firebaseapp.com',
    storageBucket: 'my-n-n.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnT9I-Cb_Z-iSkMs5doBbLt09iT-iE_uM',
    appId: '1:84806354543:android:3011a2c65c79509bff2f9a',
    messagingSenderId: '84806354543',
    projectId: 'my-n-n',
    storageBucket: 'my-n-n.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMI0mD1JQBFYu2bj5yditDsAtFSKRNpA',
    appId: '1:84806354543:ios:b2f19ca55875710fff2f9a',
    messagingSenderId: '84806354543',
    projectId: 'my-n-n',
    storageBucket: 'my-n-n.appspot.com',
    iosClientId: '84806354543-2k5rfpr0i9ibddngqh3j60t3ndsmh2bc.apps.googleusercontent.com',
    iosBundleId: 'com.vibho.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMI0mD1JQBFYu2bj5yditDsAtFSKRNpA',
    appId: '1:84806354543:ios:922c05d26b4a9c13ff2f9a',
    messagingSenderId: '84806354543',
    projectId: 'my-n-n',
    storageBucket: 'my-n-n.appspot.com',
    iosClientId: '84806354543-99ooti1e0vc3b954js4voak0tar6kuiq.apps.googleusercontent.com',
    iosBundleId: 'com.vibho.mynote.RunnerTests',
  );
}
